### ISSUE TITLE
Bug: Search with filter - dosn't work if filter has blanks

### ISSUE THREAD

**Issue by JankKeks** [T-Systems-MMS/phonebook#12] opened 2019-05-08 09:09 UTC
Search/Filter with strings with blank "%20" - result is empty
Sample: ?orgUnit=BU%20DW

**Comment by mschwrdtnr** [comment] 2019-06-21 15:24
I tested several things and the problem is only happening when the fields are object properties.

**Comment by DanielHabenicht** [comment] 2019-06-25 21:33
Fixed in version 1.18.5

**Closed by DanielHabenicht** 2019-06-25 21:33 UTC
Labels: bug
