### ISSUE TITLE
Make List-View work

### ISSUE THREAD

**Issue by mschwrdtnr** [T-Systems-MMS/phonebook#287] opened 2019-09-13 11:14 UTC
There is an option to change the layout of the results in the settings but this feature isn't implemented yet.
![image](https://user-images.githubusercontent.com/39745446/64858677-5a16f280-d628-11e9-9273-44713b9e8bde.png)

**Comment by DanielHabenicht** [comment] 2020-03-26 20:09
duplicate of https://github.com/T-Systems-MMS/phonebook/issues/176

**Closed by DanielHabenicht** 2020-03-26 20:09 UTC
Labels: feature, prio-5
